.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. infinitum_qt test_infinitum_qt
clean: FORCE
	$(MAKE) -C .. infinitum_qt_clean test_infinitum_qt_clean
check: FORCE
	$(MAKE) -C .. test_infinitum_qt_check
infinitum-qt infinitum-qt.exe: FORCE
	 $(MAKE) -C .. infinitum_qt
